### ISSUE TITLE
The license is missing in the LangBench repository

### ISSUE THREAD

**Issue by Akash-Nayak** [dsrg-uoft/LangBench#1]
Hi, can the license file be please added in the LangBench repository which has been used in the [Investigating Managed Language Runtime Performance](https://www.usenix.org/publications/loginonline/investigating-managed-language-runtime-performance) paper, so that the researchers/students/developers know if it the code can be re-used or not. Thank you very much in advance!!

**Comment by Akash-Nayak** [comment]
Hello @davidlion, we are actually planning to submit a paper in a conference and cite LangBench in our paper. We were looking for the License of the `LangBench`, but could not find it. The paper submission deadline is 9th June 2023, and it will be really very helpful if the license can be added to this repository as earliest as possible.

**Comment by davidlion** [comment]
Hi @Akash-Nayak , I added an Apache 2.0 license file. Sorry about forgetting to originally include it.

**Comment by Akash-Nayak** [comment]
> Hi @Akash-Nayak , I added an Apache 2.0 license file. Sorry about forgetting to originally include it.

Hi @davidlion.. Thank you very much for the prompt response and action!! :-)
